version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jobsity
      - POSTGRES_PASSWORD=jobsity
      - POSTGRES_DB=jobsitychatdb
    ports:
      - 5432:5432

  rabbitmq:
    image: "rabbitmq:3"
    hostname: rabbit
    labels:
      NAME: "rabbit"
    ports:
      - 5672:5672
      - 15672:15672

  web:
    build: ./web
    links:
      - rabbitmq
      - db
    depends_on:
      - db
      - rabbitmq
    command: bash -c 'while !/dev/tcp/db/5432; do sleep 1; done; python3 api.py'
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  bot:
    build: ./bot
    command: python3 bot.py
    links:
      - rabbitmq
      - web
    volumes:
      - ./bot/:/usr/src/bot/
